### ISSUE TITLE
Is malnutrition a negative effect?

### ISSUE THREAD

**Issue by 19300000** [WesCook/Nutrition#259]
Why does the potion core module's dispel clear it?

**Comment by 19300000** [comment]
avaritia module's armor cannot clear it

**Comment by WesCook** [comment]
Malnourished is indeed a negative effect, and should be classified as such in the game.  While double checking that, I was surprised to see that Nourished was _not_ marked as beneficial.  I've corrected that, but will likely not create a release for it unless there's something more pressing to include.  Setting up Forge's build process is... an ordeal.

As for Potion Core and Avaritia, I can't comment on those mods, but it's expected that they'd be unable to clear a potion effect from Nutrition as they're being constantly reapplied.  You need to correct your nutritional deficiency, not just clear away the negative effects.

**Comment by 19300000** [comment]
> Malnourished is indeed a negative effect, and should be classified as such in the game. While double checking that, I was surprised to see that Nourished was _not_ marked as beneficial. I've corrected that, but will likely not create a release for it unless there's something more pressing to include. Setting up Forge's build process is... an ordeal.
> 
> As for Potion Core and Avaritia, I can't comment on those mods, but it's expected that they'd be unable to clear a potion effect from Nutrition as they're being constantly reapplied. You need to correct your nutritional deficiency, not just clear away the negative effects.

Well, actually, I was going to make both dispel and malnutrition work at the same time when the nutrient index reaches a certain threshold, the effect of dispel is to eliminate all positive effects, but I didn't expect malnutrition to be a positive effect, I've already tried 4.9.0 and the dispel still clears malnutrition

**Comment by 19300000** [comment]
> Malnourished is indeed a negative effect, and should be classified as such in the game. While double checking that, I was surprised to see that Nourished was _not_ marked as beneficial. I've corrected that, but will likely not create a release for it unless there's something more pressing to include. Setting up Forge's build process is... an ordeal.
> 
> As for Potion Core and Avaritia, I can't comment on those mods, but it's expected that they'd be unable to clear a potion effect from Nutrition as they're being constantly reapplied. You need to correct your nutritional deficiency, not just clear away the negative effects.

Well, actually, I was going to make both dispel and malnutrition work at the same time when the nutritional index reaches a certain threshold, the effect of dispel is to eliminate all positive effects, but I didn't expect malnutrition to be a positive effect, I tried the new patch you released, the dispel will still clear malnutrition, because malnutrition is still not counted as a negative effect?

**Comment by 19300000** [comment]
> Malnourished is indeed a negative effect, and should be classified as such in the game. While double checking that, I was surprised to see that Nourished was _not_ marked as beneficial. I've corrected that, but will likely not create a release for it unless there's something more pressing to include. Setting up Forge's build process is... an ordeal.
> 
> As for Potion Core and Avaritia, I can't comment on those mods, but it's expected that they'd be unable to clear a potion effect from Nutrition as they're being constantly reapplied. You need to correct your nutritional deficiency, not just clear away the negative effects.

Well, actually, I was going to make both the dispersal and the malnutrition kick in when the nutrient index reaches a certain threshold.  The effect of dispersal is to eliminate all positive effects, but I did not expect malnutrition to be a positive effect.  I tried the new patch you released, Dispel will still clear malnutrition because malnutrition is still not counted as a negative effect?

**Comment by WesCook** [comment]
Malnourished [does not receive](https://github.com/WesCook/Nutrition/blob/1.12/src/main/java/ca/wescook/nutrition/potions/ModPotions.java#L36) a `.setBeneficial()` call, so it should not be considered a positive effect.  I can't tell you why that particular cross-mod interaction isn't working as expected, but applying a potion effect that clears other potions does seem a little error-prone.

**Comment by 19300000** [comment]
> Malnourished [does not receive](https://github.com/WesCook/Nutrition/blob/1.12/src/main/java/ca/wescook/nutrition/potions/ModPotions.java#L36) a call, so it should not be considered a positive effect. I can't tell you why that particular cross-mod interaction isn't working as expected, but applying a potion effect that clears other potions does seem a little error-prone.`.setBeneficial()`

Ok, I see. Thank you for your answer. I will try other ways to solve the problem
